# Generated by Django 5.1.1 on 2025-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('General', 'General Ward'), ('Private', 'Private Room'), ('ICU', 'Intensive Care Unit'), ('CCU', 'Cardiac Care Unit'), ('Pediatric', 'Pediatric Ward')], default='General', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('is_occupied', models.BooleanField(default=False)),
                ('current_patient', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('wing', models.CharField(blank=True, max_length=10, null=True)),
                ('maintenance_required', models.BooleanField(default=False)),
            ],
        ),
    ]
