# Generated by Django 5.1.1 on 2025-03-26 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospital.room'),
        ),
    ]
