# Generated by Django 5.1.1 on 2025-06-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_alter_room_options_remove_room_maintenance_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrequest',
            name='expected_duration',
            field=models.PositiveIntegerField(default=1, help_text='Expected stay duration in days'),
        ),
    ]
