# Generated by Django 5.1.1 on 2025-06-04 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_roomrequest_expected_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrequest',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_requests', to='hospital.appointment'),
        ),
    ]
